[project]
title = "Vera C. Rubin Observatory Documentation for Data Preview 0.3"
copyright = "2015-2022 Association of Universities for Research in Astronomy, Inc. (AURA)"
author = "Vera C. Rubin Observatory"
base_url = "https://dp0-3.lsst.io"
github_url = "https://github.com/lsst/dp0-3"
github_default_branch = "main"

[sphinx.linkcheck]
ignore = [
    "https://arxiv.org/pdf/.*#",
    "http://localhost",
	"https://dp0-3.lsst.io/v/",
]
